/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as PcsRouteImport } from './routes/pcs'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as PcsIndexRouteImport } from './routes/pcs/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as SessionsNewRouteImport } from './routes/sessions/new'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as PcsNewRouteImport } from './routes/pcs/new'
import { Route as PcsPcIdRouteImport } from './routes/pcs/$pcId'
import { Route as ClientsNewRouteImport } from './routes/clients/new'
import { Route as ClientsClientPhoneRouteImport } from './routes/clients/$clientPhone'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const PcsRoute = PcsRouteImport.update({
  id: '/pcs',
  path: '/pcs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const PcsIndexRoute = PcsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PcsRoute,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsRoute,
} as any)
const SessionsNewRoute = SessionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => SessionsRoute,
} as any)
const PcsNewRoute = PcsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PcsRoute,
} as any)
const PcsPcIdRoute = PcsPcIdRouteImport.update({
  id: '/$pcId',
  path: '/$pcId',
  getParentRoute: () => PcsRoute,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ClientsRoute,
} as any)
const ClientsClientPhoneRoute = ClientsClientPhoneRouteImport.update({
  id: '/$clientPhone',
  path: '/$clientPhone',
  getParentRoute: () => ClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/pcs': typeof PcsRouteWithChildren
  '/sessions': typeof SessionsRouteWithChildren
  '/clients/$clientPhone': typeof ClientsClientPhoneRoute
  '/clients/new': typeof ClientsNewRoute
  '/pcs/$pcId': typeof PcsPcIdRoute
  '/pcs/new': typeof PcsNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/pcs/': typeof PcsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients/$clientPhone': typeof ClientsClientPhoneRoute
  '/clients/new': typeof ClientsNewRoute
  '/pcs/$pcId': typeof PcsPcIdRoute
  '/pcs/new': typeof PcsNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/clients': typeof ClientsIndexRoute
  '/pcs': typeof PcsIndexRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRouteWithChildren
  '/pcs': typeof PcsRouteWithChildren
  '/sessions': typeof SessionsRouteWithChildren
  '/clients/$clientPhone': typeof ClientsClientPhoneRoute
  '/clients/new': typeof ClientsNewRoute
  '/pcs/$pcId': typeof PcsPcIdRoute
  '/pcs/new': typeof PcsNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRoute
  '/sessions/new': typeof SessionsNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/pcs/': typeof PcsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/pcs'
    | '/sessions'
    | '/clients/$clientPhone'
    | '/clients/new'
    | '/pcs/$pcId'
    | '/pcs/new'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/clients/'
    | '/pcs/'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients/$clientPhone'
    | '/clients/new'
    | '/pcs/$pcId'
    | '/pcs/new'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/clients'
    | '/pcs'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/pcs'
    | '/sessions'
    | '/clients/$clientPhone'
    | '/clients/new'
    | '/pcs/$pcId'
    | '/pcs/new'
    | '/sessions/$sessionId'
    | '/sessions/new'
    | '/clients/'
    | '/pcs/'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  PcsRoute: typeof PcsRouteWithChildren
  SessionsRoute: typeof SessionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pcs': {
      id: '/pcs'
      path: '/pcs'
      fullPath: '/pcs'
      preLoaderRoute: typeof PcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/pcs/': {
      id: '/pcs/'
      path: '/'
      fullPath: '/pcs/'
      preLoaderRoute: typeof PcsIndexRouteImport
      parentRoute: typeof PcsRoute
    }
    '/clients/': {
      id: '/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/sessions/new': {
      id: '/sessions/new'
      path: '/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof SessionsNewRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/pcs/new': {
      id: '/pcs/new'
      path: '/new'
      fullPath: '/pcs/new'
      preLoaderRoute: typeof PcsNewRouteImport
      parentRoute: typeof PcsRoute
    }
    '/pcs/$pcId': {
      id: '/pcs/$pcId'
      path: '/$pcId'
      fullPath: '/pcs/$pcId'
      preLoaderRoute: typeof PcsPcIdRouteImport
      parentRoute: typeof PcsRoute
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/clients/$clientPhone': {
      id: '/clients/$clientPhone'
      path: '/$clientPhone'
      fullPath: '/clients/$clientPhone'
      preLoaderRoute: typeof ClientsClientPhoneRouteImport
      parentRoute: typeof ClientsRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsClientPhoneRoute: typeof ClientsClientPhoneRoute
  ClientsNewRoute: typeof ClientsNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientPhoneRoute: ClientsClientPhoneRoute,
  ClientsNewRoute: ClientsNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface PcsRouteChildren {
  PcsPcIdRoute: typeof PcsPcIdRoute
  PcsNewRoute: typeof PcsNewRoute
  PcsIndexRoute: typeof PcsIndexRoute
}

const PcsRouteChildren: PcsRouteChildren = {
  PcsPcIdRoute: PcsPcIdRoute,
  PcsNewRoute: PcsNewRoute,
  PcsIndexRoute: PcsIndexRoute,
}

const PcsRouteWithChildren = PcsRoute._addFileChildren(PcsRouteChildren)

interface SessionsRouteChildren {
  SessionsSessionIdRoute: typeof SessionsSessionIdRoute
  SessionsNewRoute: typeof SessionsNewRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsSessionIdRoute: SessionsSessionIdRoute,
  SessionsNewRoute: SessionsNewRoute,
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRouteWithChildren,
  PcsRoute: PcsRouteWithChildren,
  SessionsRoute: SessionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
